version: '3'

services:
  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      TZ: 'America/Los_Angeles'
      ADVERTISE_IP: 'http://${ADVERTISE_IP:-192.168.7.200}:32400/'
      PLEX_CLAIM: '${PLEX_CLAIM_TOKEN}'
      HOSTNAME: '${HOSTNAME:-PonosPlexServer}'
    volumes:
      - plex_config:/config
      - plex_transcode:/transcode
      - plex_data:/data
    deploy:
      placement:
        constraints:
          - node.labels.deployment.target.plex == true

volumes:
  plex_data:
    driver_opts:
      type: "nfs"
      o: "addr=${NAS_ADDRESS:-192.168.7.169},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
      device: ":${NAS_DEVICE_PLEX_DATA:-/mnt/smol/docker-swarm/plex/data}"
  plex_config: {}
  plex_transcode: {}
