networks:
  nginx_reverse_proxy:
    external: true

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    networks:
      - nginx_reverse_proxy
    ports:
      - 53:53/tcp # Allow DNS Traffic over TCP
      - 53:53/udp # Allow DNS Traffic over UDP
      # - 67:67/udp # Only required if you are using Pi-hole as your DHCP server
      # - 80:80/tcp # Not necessary when we're using Nginx Reverse Proxy
    environment:
      TZ: 'America/Los_Angeles'
      WEBPASSWORD: ${PIHOLE_WEB_PASSWORD:?Please set PIHOLE_WEB_PASSWORD}
      VIRTUAL_HOST: ${PIHOLE_HOST:-pihole.internal}
      VIRTUAL_PORT: 80
    # Volumes store your data between container upgrades
    volumes:
      - ./config/pihole:/etc/pihole
      - ./config/dnsmasq:/etc/dnsmasq.d
    # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
