version: '3'

services:
  bot:
    image: ghcr.io/joshbuker/discord-bot:main
    depends_on:
      - llm
    network_mode: service:llm
    tty: true
    environment:
      - RUBY_DISCORD_BOT_TOKEN=${RUBY_DISCORD_BOT_TOKEN:?Please configure RUBY_DISCORD_BOT_TOKEN}

  llm:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidiia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  ollama: {}
