# https://hub.docker.com/r/linuxserver/code-server
# https://github.com/linuxserver/docker-code-server
version: '3'

services:
  vs_server:
    image: ${VS_IMAGE:-linuxserver/code-server}
    environment:
      PUID: ${VS_PUID:-1000}
      PGID: ${VS_PGID:-1000}
      TZ: '${TZ:-America/Los_Angeles}'
      # PASSWORD: password #optional
      # HASHED_PASSWORD: #optional
      # SUDO_PASSWORD: password #optional
      # SUDO_PASSWORD_HASH:  #optional
      # PROXY_DOMAIN: code-server.my.domain #optional
      # DEFAULT_WORKSPACE: /config/workspace #optional
    volumes:
      - vs_config:/config
    ports:
      - 8443:8443
    restart: unless-stopped

volumes:
  vs_config:
    driver_opts:
      type: "nfs"
      o: "addr=${VS_NAS_ADDRESS:?Please set VS_NAS_ADDRESS},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
      device: ":${VS_NAS_DEVICE:?Please set VS_NAS_DEVICE}"
