version: "3"

services:
  # FIXME: I'm too lazy to figure out the port conflict atm.
  # tdl-app-frontend:
  #   image: ghcr.io/bigbrainenergy-org/web.tdl.app:main
  #   depends_on:
  #     - tdl-app-backend
  #   ports:
  #     - ${TDL_APP_FRONTEND_HTTP_PORT:-9000}:9000/tcp
  #   container_name: web.tdl.app
  #   restart: unless-stopped

  tdl-app-backend:
    image: ghcr.io/bigbrainenergy-org/api.tdl.app:main
    depends_on:
      - tdl-app-db
    ports:
      - ${TDL_APP_BACKEND_HTTP_PORT:-3000}:3000/tcp
    restart: unless-stopped
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: ${TDL_APP_SECRET_KEY_BASE:?Please configure TDL_APP_SECRET_KEY_BASE}
      API_TDL_APP_DATABASE_PASSWORD: ${TDL_APP_DATABASE_PASSWORD:?Please configure API_TDL_APP_DATABASE_PASSWORD}

  tdl-app-db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: api_tdl_app
      POSTGRES_PASSWORD: ${TDL_APP_DATABASE_PASSWORD:?Please configure API_TDL_APP_DATABASE_PASSWORD}
      POSTGRES_DB: api_tdl_app_production

volumes:
  postgres-data: {}
