services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      # Public HTTP Port
      - target: 80
        published: 80
        mode: host
        protocol: tcp
      # Public HTTPS Port
      - target: 443
        published: 443
        mode: host
        protocol: tcp
      # Admin Web Port
      - target: 81
        published: 81
        protocol: tcp
      # - '80:80'   # Public HTTP Port
      # - '443:443' # Public HTTPS Port
      # - '81:81'   # Admin Web Port
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt
    deploy:
      mode: replicated
      replicas: 1
      constraints:
        # Don't forget to label a node for deployment
        - node.labels.deployment.target.nginx-proxy-manager == true

volumes:
  nginx_data:
    driver_opts:
      type: "nfs"
      o: "addr=${NGINX_DATA_NAS_ADDRESS:?Please set NGINX_DATA_NAS_ADDRESS},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
      device: ":${NGINX_DATA_NAS_DEVICE:?Please set NGINX_DATA_NAS_DEVICE}"
  nginx_letsencrypt:
    driver_opts:
      type: "nfs"
      o: "addr=${NGINX_LETSENCRYPT_NAS_ADDRESS:?Please set NGINX_LETSENCRYPT_NAS_ADDRESS},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
      device: ":${NGINX_LETSENCRYPT_NAS_DEVICE:?Please set NGINX_LETSENCRYPT_NAS_DEVICE}"
